language: node_js
node_js:
- 'node'
- '5'
- '4'
- '0.12'
- 'iojs'
env:
- CXX=g++-4.8
sudo: false
os:
- linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - autoconf
install:
- wget -O aerospike-server.tgz http://www.aerospike.com/download/server/3.10.1.3/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
- sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
- sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ..
- cd instance2
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ../..
script:
- npm install
- OPTIONS="--timeout 2000" npm test
notifications:
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
  hipchat:
    rooms:
      secure: C2zSj8z9fdfszR5Xl2Fjdj2Pno/x0Vc8Gl2ba4EiYrgoXNdEV2Cv7Ic3wwYj4giUyzzfeCzQ7FdziidM2WD6MSGkgSOJKqoVzRt7gYH3drABAw29kfyLJN8izN3mOmmLjuDUIBQ5XGrq3AQTKiLuCHVJDWrrGYSJPCkcDU/eo8I=
  slack:
    secure: BMIMHhqOMQnP7STsq/5WDoTKUlvB0pWCn6g6YnqKmVN2v2tMoTIBEmJlleMXBEL+0Ou4dLUmTmQKzzpiAw9tXtvgIjVh3luE+tM2QLJfwLqGshRemqwtF7DSzv5+UYEiZh0g18pQrk3HUJdD7BkU1LKkdjorgxC4rsnt+7Iz8Z0=
