language: node_js
node_js:
- '0.10'
install:
- sudo apt-get install autoconf libssl-dev liblua5.1 liblua5.1-dev
- sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so /usr/lib/liblua.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.a /usr/lib/liblua.a
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- sudo ./bin/aerospike start
- cd ..
- cd instance2
- sudo ./bin/aerospike start
- cd ../..
- sleep 3
script:
- asinfo -v 'set-config:context=namespace;id=test;ldt-enabled=true'
- npm install
- npm test
notifications:
  slack:
    secure: BMIMHhqOMQnP7STsq/5WDoTKUlvB0pWCn6g6YnqKmVN2v2tMoTIBEmJlleMXBEL+0Ou4dLUmTmQKzzpiAw9tXtvgIjVh3luE+tM2QLJfwLqGshRemqwtF7DSzv5+UYEiZh0g18pQrk3HUJdD7BkU1LKkdjorgxC4rsnt+7Iz8Z0=
