on:
  workflow_call:
    inputs:
      passed-dev-tag:
        type: string
        description: Dev tag to fast forward the stage branch to
        required: true
    secrets:
      # Used to bump version in Github
      CLIENT_BOT_PAT:
        required: true
      # Used to upload to JFrog
      JFROG_PLATFORM_URL:
        required: true

jobs:
  ff-stage-to-dev-tag:
    name: Fast forward stage branch to the dev tag that passed stage testing
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      ref_to_merge: ${{ inputs.passed-dev-tag }}
      base_branch: ${{ vars.STAGE_BRANCH_NAME }}
    secrets: inherit

  promote-dev-build-to-rc:
    name: Bump (promote) the dev version to an RC version in the stage branch
    needs: ff-stage-to-dev-tag
    uses: ./.github/workflows/bump-version.yml
    with:
      change: 'promote-dev-build-to-rc'
      ref: ${{ vars.STAGE_BRANCH_NAME }}
    secrets: inherit

  rebuild-artifacts-with-rc-version:
    needs: promote-dev-build-to-rc
    uses: ./.github/workflows/build-artifacts.yml
    secrets: inherit

  upload-rc-artifacts-to-jfrog:
    needs: [
      rebuild-artifacts-with-rc-version,
      # We need the new RC version to label the build in JFrog
      promote-dev-build-to-rc
    ]
    name: Upload artifacts to JFrog
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      version: ${{ needs.promote-dev-build-to-rc.outputs.new_version }}
    secrets: inherit

  # See reason for deleting artifacts in dev-workflow-p2.yml
  delete-artifacts:
    needs: upload-rc-artifacts-to-jfrog
    uses: ./.github/workflows/delete-artifacts.yml

  ff-dev-to-stage:
    name: Fast forward dev branch to stage branch to include the bump to RC commit
    needs: promote-dev-build-to-rc
    uses: ./.github/workflows/fast-forward-merge.yml
    with:
      ref_to_merge: origin/${{ vars.STAGE_BRANCH_NAME }}
      base_branch: ${{ vars.DEV_BRANCH_NAME }}
    secrets: inherit
