name: Stage workflow

# 1. When a PR review is requested, run tests on that PR
# 2. If all of the tests pass, allow the PR to be merged into `dev`
# 3. Whenever a PR is merged to `dev`, bump version number in `dev`

on:
  pull_request:
    branches:
      - 'stage'
      - 'stage*'
    paths-ignore:
      - 'docs/**'
      - 'aerospike-stubs/**'

  # So we can test changes to the test-server-rc workflow
  workflow_dispatch:
    inputs:
      run_server_release_tests:
        description: 'DEBUG: Run server release tests in build-wheels workflow?'
        type: boolean
        default: false

jobs:
  get-jfrog-dev-version:
    uses: ./.github/workflows/get-jfrog-dev-version.yml
    secrets: inherit

  test-with-server-release:
    uses: ./.github/workflows/test-artifacts.yml
    with:
      version: ${{ needs.get-jfrog-dev-version.outputs.dev_version }}
      run_tests: true
    needs: [
      get-jfrog-dev-version,
    ]
    secrets: inherit

  bump-dev-number:
    uses: ./.github/workflows/bump-stage-version.yml
    needs: [
      get-jfrog-dev-version,
      test-with-server-release,
    ]
    secrets: inherit

  reupload-stage-to-jfrog:
    name: Upload artifacts to JFrog
    needs: [
      get-jfrog-dev-version,
      test-with-server-release,
      bump-dev-number
    ]
    uses: ./.github/workflows/reupload-to-jfrog.yml
    with:
      old_version: ${{ needs.get-jfrog-dev-version.outputs.dev_version }}
      #new_version: 6.2.1-rc.20
      new_version: ${{ needs.bump-dev-number.outputs.new_stage_version }}
      pipeline-stage: 'stage'
    secrets: inherit

  reupload-stage-to-jfrog-npm-repo:
    name: Upload artifacts to JFrog
    needs: [
      get-jfrog-dev-version,
      test-with-server-release,
      bump-dev-number,
      reupload-stage-to-jfrog
    ]
    uses: ./.github/workflows/upload-to-jfrog-npm-repo.yml
    with:
      #new_version: 6.2.1-rc.20
      new_version: ${{ needs.bump-dev-number.outputs.new_stage_version }}
      pipeline-stage: 'stage'
    secrets: inherit
